-- Table: country
CREATE TABLE IF NOT EXISTS country
(
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 1),
  name VARCHAR(255) NOT NULL,
  CONSTRAINT pk_country_id PRIMARY KEY (id),
);

-- Table: hotel

CREATE TABLE IF NOT EXISTS hotel
(
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 1),
  name      VARCHAR(255) NOT NULL,

  stars     SMALLINT     NOT NULL,
  website   VARCHAR(255),
  lalitude  DECIMAL      NOT NULL,
  longitude DECIMAL      NOT NULL,
  features  VARCHAR(255) NOT NULL,
  CONSTRAINT pk_hotel_id PRIMARY KEY (id)
);

-- Table: tour

CREATE TABLE IF NOT EXISTS tour
(
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 1),
  photo       VARCHAR(255),
  date        DATE         NOT NULL,
  duration    SMALLINT     NOT NULL,
  description VARCHAR(255) NOT NULL,
  cost        DECIMAL      NOT NULL,
  tour_type   VARCHAR(255) NOT NULL,
  hotel_id    BIGINT       NOT NULL,
  country_id  BIGINT       NOT NULL,
  CONSTRAINT pk_tour_id PRIMARY KEY (id),
  CONSTRAINT fk_hotel_id FOREIGN KEY (hotel_id)
  REFERENCES hotel (id)
  ON UPDATE CASCADE
  ON DELETE CASCADE,
  CONSTRAINT fk_country_id FOREIGN KEY (country_id)
  REFERENCES country (id)
  ON UPDATE CASCADE
  ON DELETE CASCADE
);

-- Table: client

CREATE TABLE IF NOT EXISTS client
(
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 1),
  login    VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  CONSTRAINT pk_client_id PRIMARY KEY (id),
  CONSTRAINT login_uq UNIQUE (login),
  role     VARCHAR(8)   NOT NULL
);

-- Table: user_tour

CREATE TABLE IF NOT EXISTS client_tour
(
  client_id BIGINT NOT NULL,
  tour_id   BIGINT NOT NULL,
  CONSTRAINT pk_client_tour PRIMARY KEY (client_id, tour_id),
  CONSTRAINT fk_tour_c_id FOREIGN KEY (tour_id)
  REFERENCES tour (id)
  ON UPDATE CASCADE
  ON DELETE CASCADE,
  CONSTRAINT fk_client_t_id FOREIGN KEY (client_id)
  REFERENCES client (id)
  ON UPDATE CASCADE
  ON DELETE CASCADE
);

-- Table: review

CREATE TABLE IF NOT EXISTS review
(
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 1),
  date      DATE         NOT NULL,
  text      VARCHAR(255) NOT NULL,
  tour_id   BIGINT       NOT NULL,
  client_id BIGINT       NOT NULL,
  CONSTRAINT pk_review_id PRIMARY KEY (id),
  CONSTRAINT fk_tour_id FOREIGN KEY (tour_id)
  REFERENCES tour (id)
  ON UPDATE CASCADE
  ON DELETE CASCADE,
  CONSTRAINT fk_client_id FOREIGN KEY (client_id)
  REFERENCES client (id)
  ON UPDATE CASCADE
  ON DELETE CASCADE
);
